USE BD_INMUEBLES
DECLARE @TABLE_TIPO_INMUEBLE TABLE(DESCRIPCION varchar(250),ELIMINADO bit)
INSERT INTO @TABLE_TIPO_INMUEBLE(DESCRIPCION,ELIMINADO)
SELECT 'CASA',0 UNION ALL
SELECT 'DEPARTAMENTO',0 UNION ALL
SELECT 'TERRENO',0
DELETE T
FROM @TABLE_TIPO_INMUEBLE T
WHERE DESCRIPCION IN (SELECT FA.DESCRIPCION FROM TIPO_INMUEBLE FA)
INSERT INTO TIPO_INMUEBLE(DESCRIPCION,ELIMINADO)
select DESCRIPCION,ELIMINADO
FROM @TABLE_TIPO_INMUEBLE